#!/usr/bin/env bash
#Install and configure HAproxy
sudo apt-get update
sudo apt-get -y install haproxy
sudo bash -c 'echo "frontend web_front
   bind *:80
   mode http
   default_backend web_back

   backend web_back
   balance roundrobin
   server 456242-web-01 35.168.7.64:80 check
   server 456242-web-02 34.204.81.91:80 check
" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
