#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".
count=1
while((count <= 10))
do
        echo "Best School"
    if ((count == 9))
    then
        echo "Hi"
    fi
    ((count++))
done
